2021-05-11 15:08:51,962-log.py:[31]-[INFO]-test succeed
2021-05-11 17:13:00,073-log.py:[31]-[INFO]-test succeed
2021-05-11 17:53:19,193-log.py:[31]-[INFO]-test succeed
2021-05-11 18:08:54,292-log.py:[27]-[INFO]-test succeed
2021-05-11 18:12:48,958-log.py:[27]-[INFO]-test succeed
2021-05-11 18:14:05,625-readexcel.py:[16]-[ERROR]-reading home_page_elements failed 
Traceback (most recent call last):
  File "D:/UiTest/xiaozutest/retail/test_case/models/readexcel.py", line 11, in __init__
    self.workbook = xlrd.open_workbook(self.dataFile)
  File "C:\Users\Administrator.LAPTOP-33BS7RCR\AppData\Local\Programs\Python\Python38\lib\site-packages\xlrd\__init__.py", line 166, in open_workbook
    file_format = inspect_format(filename, file_contents)
  File "C:\Users\Administrator.LAPTOP-33BS7RCR\AppData\Local\Programs\Python\Python38\lib\site-packages\xlrd\__init__.py", line 60, in inspect_format
    with open(path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\UiTest\\retail\\data\\testdata\\elementData.xlsx'
2021-05-11 18:15:14,225-readexcel.py:[16]-[ERROR]-reading home_page_elements failed 
Traceback (most recent call last):
  File "D:/UiTest/xiaozutest/retail/test_case/models/readexcel.py", line 11, in __init__
    self.workbook = xlrd.open_workbook(self.dataFile)
  File "C:\Users\Administrator.LAPTOP-33BS7RCR\AppData\Local\Programs\Python\Python38\lib\site-packages\xlrd\__init__.py", line 170, in open_workbook
    raise XLRDError(FILE_FORMAT_DESCRIPTIONS[file_format]+'; not supported')
xlrd.biffh.XLRDError: Excel xlsx file; not supported
2021-05-11 18:16:58,000-readexcel.py:[19]-[INFO]-reading home_page_elements succeed 
2021-05-11 18:16:58,000-readexcel.py:[28]-[INFO]-read value 1,3 in sheetName home_page_elements succeed
